version: "3.7"

services:
  traefik:
    image: traefik
    command: traefik --configFile=/app/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/app
    labels:
      - "traefik.backend=traefik"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:traefik.localhost"
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

volumes:
  traefik_data:
    name: evoluservicesbr-traefik-prod
    driver: rexray/s3fs:latest

networks:
  traefik-net:
    external: true
