version: "3.7"
services:
  ntpserver: 
    image: evoluservicesbr/ntpserver:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports: 
      - "123:123/udp"
    networks:
      - network-ntp

networks:
  network-ntp:



    