version: "3.7"

services:
  minio:
    image: evoluservicesbr/minio:latest
    container_name: minio
    restart: always
    volumes:
        - /volume:/data
    ports:
        - "8090:9000"
    environment:
      MINIO_ACCESS_KEY: 
      MINIO_SECRET_KEY:
    command: server /data
